package modelos;
// Generated 14-nov-2021 19:15:04 by Hibernate Tools 4.3.1



/**
 * Alojamiento generated by hbm2java
 */
public class Alojamiento  implements java.io.Serializable {


     private int idAlojamiento;
     private String nombre;
     private int capacidad;
     private int dormitorios;
     private int banos;
     private int terraza;
     private int piscina;
     private int aparcamiento;
     private String direccion;
     private String poblacion;
     private String provincia;
     private int idPropietario;
     private int idUsuario;

    public Alojamiento() {
    }

    public Alojamiento(String nombre, int capacidad, int dormitorios, int banos, int terraza, int piscina, int aparcamiento, String direccion, String poblacion, String provincia, int idPropietario, int idUsuario) {
       this.nombre = nombre;
       this.capacidad = capacidad;
       this.dormitorios = dormitorios;
       this.banos = banos;
       this.terraza = terraza;
       this.piscina = piscina;
       this.aparcamiento = aparcamiento;
       this.direccion = direccion;
       this.poblacion = poblacion;
       this.provincia = provincia;
       this.idPropietario = idPropietario;
       this.idUsuario = idUsuario;
    }
   
    public int getIdAlojamiento() {
        return this.idAlojamiento;
    }
    
    public void setIdAlojamiento(int idAlojamiento) {
        this.idAlojamiento = idAlojamiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }
    public int getDormitorios() {
        return this.dormitorios;
    }
    
    public void setDormitorios(int dormitorios) {
        this.dormitorios = dormitorios;
    }
    public int getBanos() {
        return this.banos;
    }
    
    public void setBanos(int banos) {
        this.banos = banos;
    }
    public int getTerraza() {
        return this.terraza;
    }
    
    public void setTerraza(int terraza) {
        this.terraza = terraza;
    }
    public int getPiscina() {
        return this.piscina;
    }
    
    public void setPiscina(int piscina) {
        this.piscina = piscina;
    }
    public int getAparcamiento() {
        return this.aparcamiento;
    }
    
    public void setAparcamiento(int aparcamiento) {
        this.aparcamiento = aparcamiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public int getIdPropietario() {
        return this.idPropietario;
    }
    
    public void setIdPropietario(int idPropietario) {
        this.idPropietario = idPropietario;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Override
    public String toString() {
        return "Alojamiento{" + "idAlojamiento=" + idAlojamiento + ", nombre=" + nombre + ", capacidad=" + capacidad + ", dormitorios=" + dormitorios + ", banos=" + banos + ", terraza=" + terraza + ", piscina=" + piscina + ", aparcamiento=" + aparcamiento + ", direccion=" + direccion + ", poblacion=" + poblacion + ", provincia=" + provincia + ", idPropietario=" + idPropietario + ", idUsuario=" + idUsuario + '}';
    }




}


