package modelos;
// Generated 14-nov-2021 19:15:04 by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String apellidos;
     private String dni;
     private String pasaporte;
     private String nacionalidad;
     private String telefono;
     private String email;
     private int idUsuario;

    public Cliente() {
    }

    public Cliente(int idCliente, String nombre, String apellidos, String dni, String pasaporte, String nacionalidad, String telefono, String email, int idUsuario) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.dni = dni;
       this.pasaporte = pasaporte;
       this.nacionalidad = nacionalidad;
       this.telefono = telefono;
       this.email = email;
       this.idUsuario = idUsuario;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getPasaporte() {
        return this.pasaporte;
    }
    
    public void setPasaporte(String pasaporte) {
        this.pasaporte = pasaporte;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


