package modelos;
// Generated 29-nov-2021 20:55:02 by Hibernate Tools 4.3.1



/**
 * Propietarios generated by hbm2java
 */
public class Propietarios  implements java.io.Serializable {


     private int idPropietario;
     private String nombre;
     private String apellidos;
     private String nif;
     private String telefono;
     private String email;
     private int idUsuario;

    public Propietarios() {
    }

    public Propietarios(int idPropietario, String nombre, String apellidos, String nif, String telefono, String email, int idUsuario) {
       this.idPropietario = idPropietario;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.nif = nif;
       this.telefono = telefono;
       this.email = email;
       this.idUsuario = idUsuario;
    }
   
    public int getIdPropietario() {
        return this.idPropietario;
    }
    
    public void setIdPropietario(int idPropietario) {
        this.idPropietario = idPropietario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


